### 启动:sudo docker-compose up -d
### 停止:sudo docker-compose down
version: "3"
services:
  nacos:
    ### sudo docker logs -f nacos203
    hostname: nacos
    image: nacos/nacos-server:v2.0.3
    container_name: nacos203
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=rm-3ns6uqke633926jph.mysql.rds.aliyuncs.com
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=oBi&G%f#fL43R58S
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=UTC
      - JVM_XMS=512m
      - JVM_XMX=1024m
      - JVM_XMN=1024m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    restart: always