server:
  port: 9522
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sengre1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
      username: root
      password: 123456
  redis:
    host: 10.39.1.81
    port: 6379
    database: 7
# 不需要登录验证的url
login:
  auth:
    urls:
      - /sys/config
      - /sys/captcha.jpg
      - /user/register
      - /user/login
      - /product/list
      - /sys/question
      - /withdraw/callback/yypay
      - /topup/callback/yypay
      - /sys/version
      - /sys/carousel/list/*
task:
  weekreward:
    cron: 0/10 * * * * ?