server:
  port: 9522
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-3ns6uqke633926jphao.mysql.rds.aliyuncs.com:3306/sengre?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
      username: sengre
      password: KQ5BbCay4WP4Uo!x
  redis:
    host: r-3nsndkc8hujbtb5kn9pd.redis.rds.aliyuncs.com
    port: 6379
    password: IwS&jvWnH6iy4S5X
# 不需要登录验证的url
login:
  auth:
    urls:
      - /sys/config
      - /sys/captcha.jpg
      - /user/register
      - /user/login
      - /product/list
      - /sys/question
      - /withdraw/callback/yypay
      - /topup/callback/yypay
      - /sys/version
      - /sys/carousel/list/*
task:
  weekreward:
    cron: 0/10 * * * * ?